from __future__ import annotations

from types import MappingProxyType


MAX_YEARS = 3
SEASONS_PER_YEAR = 4
TOTAL_TURNS = MAX_YEARS * SEASONS_PER_YEAR
ACTIONS_PER_TURN = 2

INITIAL_RESOURCES = MappingProxyType(
    {
        "wood": 20,
        "food": 30,
        "iron": 0,
        "silver": 0,
        "fame": 0,
        "population": 8,
        "morale": 50,
        "ships": 0,
        "warriors": 0,
        "discovery": 0,
    }
)

LOW_MORALE_THRESHOLD = 20
LOW_MORALE_PRODUCTION_MULTIPLIER = 0.75

HUT_WOOD_COST = 18
HUT_RESILIENCE_GAIN = 1

TOOLS_WOOD_COST = 8
TOOLS_IRON_COST = 3
TOOLS_GAIN = 1
TOOLS_MAX = 5
TOOL_PRODUCTION_BONUS = 0.12

TRAIN_WARRIOR_FOOD_COST = 8
TRAIN_WARRIOR_IRON_COST = 2

FEAST_FOOD_COST = 12
FEAST_SILVER_COST = 2
FEAST_MORALE_GAIN = 14
FEAST_FAME_GAIN = 2

TRADE_FOOD_COST = 8
TRADE_WOOD_COST = 8
TRADE_SILVER_GAIN = 4
TRADE_IRON_GAIN = 2

SCOUT_FOOD_COST = 6
SCOUT_DISCOVERY_GAIN = 2

SHIPYARD_WOOD_COST = 45
SHIPYARD_IRON_COST = 8

LONGSHIP_WOOD_COST = 35
LONGSHIP_IRON_COST = 6
LONGSHIP_SILVER_COST = 6

EXPEDITION_FOOD_COST = 12
EXPEDITION_BASE_TARGET = 18
EXPEDITION_WARRIOR_SCORE = 3
EXPEDITION_MORALE_SCORE = 0.08
EXPEDITION_FAME_SCORE = 1
EXPEDITION_DISCOVERY_SCORE = 1.5

WIN_EXPEDITION_EARLIEST_YEAR = 3

WEAKNESS_POPULATION_THRESHOLD = 4
WEAKNESS_MORALE_THRESHOLD = 15
WEAKNESS_FOOD_THRESHOLD = 8
WEAKNESS_EVENT_LIMIT = 3

MORALE_MIN = 0
MORALE_MAX = 100

